(in-package :evdev)

(define-constant +input-event-types+
  '((#x00 . :ev-syn)
    (#x01 . :ev-key)
    (#x02 . :ev-rel)
    (#x03 . :ev-abs)
    (#x04 . :ev-msc)
    (#x05 . :ev-sw)
    (#x11 . :ev-led)
    (#x12 . :ev-snd)
    (#x14 . :ev-rep)
    (#x15 . :ev-ff)
    (#x16 . :ev-pwr)
    (#x17 . :ev-ff-status))
  :documentation "The type of an input event stored in the type field of the
Linux input_event struct in linux/include/uapi/linux/input.h. Not expected to be
used outside of this package.")

(define-constant +input-key-states+
  '((0 . :released)
    (1 . :pressed)
    (2 . :repeat))
  :documentation "Keyboard input key states as stored in the value field of the
Linux input_event struct in linux/include/uapi/linux/input.h. Not expected to be
used outside of this package.")

(define-constant +input-key-codes+
    '((0 .   (:name reserved         :glyph nil))
      (1 .   (:name esc              :glyph nil))
      (2 .   (:name 1                :glyph #\1))
      (3 .   (:name 2                :glyph #\2))
      (4 .   (:name 3                :glyph #\3))
      (5 .   (:name 4                :glyph #\4))
      (6 .   (:name 5                :glyph #\5))
      (7 .   (:name 6                :glyph #\6))
      (8 .   (:name 7                :glyph #\7))
      (9 .   (:name 8                :glyph #\8))
      (10 .  (:name 9                :glyph #\9))
      (11 .  (:name 0                :glyph #\0))
      (12 .  (:name minus            :glyph #\-))
      (13 .  (:name equal            :glyph #\=))
      (14 .  (:name backspace        :glyph #\Backspace))
      (15 .  (:name tab              :glyph #\Tab))
      (16 .  (:name q                :glyph #\q))
      (17 .  (:name w                :glyph #\w))
      (18 .  (:name e                :glyph #\e))
      (19 .  (:name r                :glyph #\r))
      (20 .  (:name t                :glyph #\t))
      (21 .  (:name y                :glyph #\y))
      (22 .  (:name u                :glyph #\u))
      (23 .  (:name i                :glyph #\i))
      (24 .  (:name o                :glyph #\o))
      (25 .  (:name p                :glyph #\p))
      (26 .  (:name leftbrace        :glyph #\[))
      (27 .  (:name rightbrace       :glyph #\]))
      (28 .  (:name enter            :glyph #\Newline))
      (29 .  (:name leftctrl         :glyph nil))
      (30 .  (:name a                :glyph #\a))
      (31 .  (:name s                :glyph #\s))
      (32 .  (:name d                :glyph #\d))
      (33 .  (:name f                :glyph #\f))
      (34 .  (:name g                :glyph #\g))
      (35 .  (:name h                :glyph #\h))
      (36 .  (:name j                :glyph #\j))
      (37 .  (:name k                :glyph #\k))
      (38 .  (:name l                :glyph #\l))
      (39 .  (:name semicolon        :glyph #\;))
      (40 .  (:name apostrophe       :glyph #\'))
      (41 .  (:name grave            :glyph #\`))
      (42 .  (:name leftshift        :glyph nil))
      (43 .  (:name backslash        :glyph #\\))
      (44 .  (:name z                :glyph #\z))
      (45 .  (:name x                :glyph #\x))
      (46 .  (:name c                :glyph #\c))
      (47 .  (:name v                :glyph #\v))
      (48 .  (:name b                :glyph #\b))
      (49 .  (:name n                :glyph #\n))
      (50 .  (:name m                :glyph #\m))
      (51 .  (:name comma            :glyph #\,))
      (52 .  (:name dot              :glyph #\.))
      (53 .  (:name slash            :glyph #\/))
      (54 .  (:name rightshift       :glyph nil))
      (55 .  (:name kpasterisk       :glyph #\*))
      (56 .  (:name leftalt          :glyph nil))
      (57 .  (:name space            :glyph #\Space))
      (58 .  (:name capslock         :glyph nil))
      (59 .  (:name f1               :glyph nil))
      (60 .  (:name f2               :glyph nil))
      (61 .  (:name f3               :glyph nil))
      (62 .  (:name f4               :glyph nil))
      (63 .  (:name f5               :glyph nil))
      (64 .  (:name f6               :glyph nil))
      (65 .  (:name f7               :glyph nil))
      (66 .  (:name f8               :glyph nil))
      (67 .  (:name f9               :glyph nil))
      (68 .  (:name f10              :glyph nil))
      (69 .  (:name numlock          :glyph nil))
      (70 .  (:name scrolllock       :glyph nil))
      (71 .  (:name kp7              :glyph nil))
      (72 .  (:name kp8              :glyph nil))
      (73 .  (:name kp9              :glyph nil))
      (74 .  (:name kpminus          :glyph nil))
      (75 .  (:name kp4              :glyph nil))
      (76 .  (:name kp5              :glyph nil))
      (77 .  (:name kp6              :glyph nil))
      (78 .  (:name kpplus           :glyph nil))
      (79 .  (:name kp1              :glyph nil))
      (80 .  (:name kp2              :glyph nil))
      (81 .  (:name kp3              :glyph nil))
      (82 .  (:name kp0              :glyph nil))
      (83 .  (:name kpdot            :glyph #\.))
      (85 .  (:name zenkakuhankaku   :glyph nil))
      (86 .  (:name 102nd            :glyph nil))
      (87 .  (:name f11              :glyph nil))
      (88 .  (:name f12              :glyph nil))
      (96 .  (:name kpenter          :glyph #\Newline))
      (97 .  (:name rightctrl        :glyph nil))
      (98 .  (:name kpslash          :glyph nil))
      (99 .  (:name sysrq            :glyph nil))
      (100 . (:name rightalt         :glyph nil))
      (101 . (:name linefeed         :glyph nil))
      (102 . (:name home             :glyph nil))
      (103 . (:name up               :glyph nil))
      (104 . (:name pageup           :glyph nil))
      (105 . (:name left             :glyph nil))
      (106 . (:name right            :glyph nil))
      (107 . (:name end              :glyph nil))
      (108 . (:name down             :glyph nil))
      (109 . (:name pagedown         :glyph nil))
      (110 . (:name insert           :glyph nil))
      (111 . (:name delete           :glyph #\Delete))
      (112 . (:name macro            :glyph nil))
      (113 . (:name mute             :glyph nil))
      (114 . (:name volumedown       :glyph nil))
      (115 . (:name volumeup         :glyph nil))
      (116 . (:name power            :glyph nil))
      (117 . (:name kpequal          :glyph #\=))
      (118 . (:name kpplusminus      :glyph nil))
      (119 . (:name pause            :glyph nil)))
  :documentation "List of key code to key symbol name and printable character.
Used to decode the code field of the Linux input_event struct defined in
linux/include/uapi/linux/input.h.")

(define-unsigned long-int 4)
(define-unsigned unsigned-short 2)
(define-unsigned unsigned-int 4)

(define-binary-class input-event ()
  ((tv_sec  :binary-type long-int)
   (tv_usec :binary-type long-int)
   (type    :binary-type unsigned-short)
   (code    :binary-type unsigned-short)
   (value   :binary-type unsigned-int)))

(defun read-event (stream)
  (let ((event (read-binary 'input-event stream)))
    (format t "~{~S~}" event)))

(defun input-event-loop (device-path)
  (with-binary-file (stream device-path :direction :input)
    (unwind-protect
         (let ((*endian* :little-endian))
           (loop
              (let ((input-event (read-binary 'input-event stream)))
                (unless input-event (return))
                (with-slots (tv_sec tv_usec type code value) input-event
                  (when (and (eq (rest (assoc type +input-event-types+))
                                 :ev-key)
                             (eq value 1))
                    (format t "time: ~S.~S type: ~S code: ~S value: ~S~%"
                            tv_sec tv_usec
                            (assoc type +input-event-types+)
                            (assoc code +input-key-codes+)
                            value)
                    (finish-output)))))))))
